apiVersion: apps/v1
kind: Deployment
metadata:
  name: miniport-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: miniport
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: miniport
    spec:
      containers:
      - name: miniport-container
        image: corletey/miniport-website:latest
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 20
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: miniport-pdb
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: miniport

